### PR TITLE
Make Tests Pass Again

### LINKED ISSUE #184: Tests Failing on Master
I cloned the repo today, and I'm seeing tests fail out of the box:

```
component:infinity-loader: it throws error when scrollable element is not found
    ✘ Should raise error

component:infinity-loader: it throws error when multiple scrollable elements are found
    ✘ Should raise error

component:infinity-loader: it throws error when scrollable is something other than nothing or string
    ✘ Promise rejected after it throws error when scrollable is something other than nothing or string: Cannot read property 'off' of undefined

    ✘ Expected 1 assertions, but 2 were run

component:infinity-loader: it checks if in view on the scroll event
    ✘ Promise rejected before it checks if in view on the scroll event: Assertion Failed: You cannot use the same root element (#ember-testing) multiple times in an Ember.Application

    ✘ Died on test #2     at testWrapper (http://localhost:7357/assets/test-support.js:6236:11)
        at test (http://localhost:7357/assets/test-support.js:6250:39)
        at Module.callback (http://localhost:7357/assets/tests.js:825:24)
        at Module.exports (http://localhost:7357/assets/vendor.js:65:34)
        at Module.build (http://localhost:7357/assets/vendor.js:115:10)
        at findModule (http://localhost:7357/assets/vendor.js:163:9)
        at requireModule (http://localhost:7357/assets/vendor.js:150:12): this.subject is not a function

    ✘ Expected 1 assertions, but 2 were run

component:infinity-loader: it checks if in view on the resize event
    ✘ Assertion after the final `assert.async` was resolved

    ✘ Expected 1 assertions, but 2 were run
```

### PR DESCRIPTION
**Pull request by jherdman**
* Port failing tests to integration tests
* Fix unbinding when no scrollable element available (e.g. the `throw`
  case)
* Move integration test to canonical location

Resolves #184

### CODE REVIEW

**Comment by hhff** [comment]
@jherdman thankyou so so much for taking this on!  I actually opened an issue at Ember CLI issue over at https://github.com/ember-cli/ember-cli/issues/6270

The recommendation was to update the Ember CLI version for the addon.  Are you down to take a stab at that?

**Comment by jherdman** [comment]
I'm attempting to in another branch on my machine. It's a fair bit of work, but I may be down for it.

How married are you to continued support for ancient Ember versions?

**Comment by hhff** [comment]
Thankyou so much @jherdman !  

I'm happy to drop 1.x support going forward (if we do that we'll go to `0.3.x` track) but I don't think there's any reason why we'd have to do that yet.

**Comment by hhff** [comment]
Let me know if you hit a road block and we can chat on it!

**Comment by hhff** [comment]
superseded by #187

**Pull request closed without merging**
