### PR TITLE
adding code coverage to readme/pull requests

### LINKED ISSUE #65: Add code coverage % changed to pull requests
It's pretty easy to do. I've added it to [ember-cli](https://github.com/ember-cli/ember-cli) and [broccoli-jscs](https://github.com/kellyselden/broccoli-jscs). Just want to see @hhff if you want it. It may require me becoming a project owner, but I don't remember. I can first try it at my current rights level.

### PR DESCRIPTION
**Pull request by kellyselden**
Fixes #65

### CODE REVIEW

**Comment by mike-north** [comment]
This may be a little more challenging for the app (ES6) code. `ember-cli` and `broccoli-jscs` are written in ES5 so they don't have to deal with this issue.

I've added coverage to [ember-cli-materialize](https://github.com/mike-north/ember-cli-materialize) using blanket, and the number (and corresponding PR check) is quite useful. The sourcemaps are wrong because it's the transpiled modules that are instrumented for coverage -- I'll get that fixed in `ember-cli-blanket` one of these days :)

**Comment by hhff** [comment]
@mike-north / @kellyselden - what's the consensus here?  I haven't had much to do with code coverage before - happy for you guys to make a decision here

**Comment by kellyselden** [comment]
@hhff This is currently dead in the water. I forgot about babel transpiling, which make this non-trivial. We can close or keep open for when I have time to take another stab at it.

**Comment by hhff** [comment]
Let's close it for now - we've got an issue as a reminder :+1: 

thankyou @kellyselden !

**Comment by mike-north** [comment]
@kellyselden if we just care about a number, I can put something in place :). The source maps will be messed up due to blanket.js instrumenting the transpiled modules (which don't exist as separate files in the build pipeline)

Example:
* PRs are instrumented: https://coveralls.io/github/mike-north/ember-cli-materialize
* The source maps are messed up https://coveralls.io/builds/3495221/source?filename=addon%2Fcomponents%2Fmd-input-date.js (this is because ES5 source is instrumented, and projected onto ES6 files)

I believe the overall coverage number (and even module coverage number) to still be quite useful, particularly in terms of making sure coverage doesn't drop significantly

**Comment by hhff** [comment]
honestly I think if we've got overall coverage then that would help a bunch tbh @mike-north

**Pull request closed without merging**
