### PR TITLE
Allow setting starting page as 0.

### PR DESCRIPTION
**Pull request by wuron**

### CODE REVIEW

**Comment by kellyselden** [comment]
I'm on board with this change, but you would want a test so it doesn't regress.

**Comment by wuron** [comment]
Added the test.

**Comment by kellyselden** [comment]
LGTM. We would need you to squash commits, then it can be merged.

**Comment by wuron** [comment]
Updated.

**Comment by kellyselden** [comment]
Thanks!

**Comment by hhff** [comment]
TY!!

**Comment by hhff** [comment]
@wuron - could you do a quick PR documenting this in the README?

**Comment by wuron** [comment]
I'm not sure what to document here. Basically it's just a bugfix cause 0 was treated as falsy value so startingPage set to 0 was overriden with 1.

**Comment by hhff** [comment]
@wuron oh right sorry just skimmed it!  as you were

**Pull request merged**
