### PR TITLE
untimelyLoading and passing block

### PR DESCRIPTION
**Pull request by mariuszzak**
I have added another property which let you start loading data before scroll is at the very bottom of page. 

The name of property can be not excellent. Do you have idea how to name it better?

### CODE REVIEW

**Comment by mariuszzak** [comment]
I have also added possibility of passing block to the component. I wasn't able to show animation during loading without this change.

**Comment by hhff** [comment]
Thanks so much @mariuszzak !  I think we should use `triggerOffset` for the property you mention!

Thankyou for adding the `{{yield}}` statement too!  Can we please put these two features in separate Pull Requests?  It's for the ssake of a clean Changelog !

**Comment by kellyselden** [comment]
Also needs tests.

**Comment by seawatts** [comment]
@mariuszzak Thank you so much for this! Can't wait for this to land!

**Comment by mariuszzak** [comment]
I'll put features in separate pull requests.

**Pull request closed without merging**
