### PR TITLE
Made _currentPage public => is now currentPage

### PR DESCRIPTION
**Pull request by dj-hedgehog**

### CODE REVIEW

**Comment by hhff** [comment]
:+1: LGTM - @kellyselden any thoughts?

**Comment by kellyselden** [comment]
Squash and then all is good.

**Comment by dj-hedgehog** [comment]
What do you mean by squash?

**Comment by hhff** [comment]
@dj-hedgehog - squashing commits means "combining all your work into a single git commit".  We do this so that our commit history and changelog accurately represents what has happened to the project over time.

This is a super useful for learning how to do it: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by dj-hedgehog** [comment]
Closed in favor of #59

**Pull request closed without merging**
