### PR TITLE
Document event hooks

### PR DESCRIPTION
**Pull request by ashrafhasson**
documented the following event hooks: `infinityModelUpdated` and `infinityModelLoaded`

### CODE REVIEW

**Comment by ashrafhasson** [comment]
Hi @hhff I'm not sure why this is failing on Travis but the tests are passing locally!

**Comment by hhff** [comment]
ahhh @ashrafhasson - the reason it's failing is because Ember 2.0 is now the "beta" that Ember Try tests against.  I guess I'll have to do some work to make this addon work against ember 2.0 beta.

grrrr

OK if we leave this hanging for a minute?  Either way, we'll need to rebase against master, as we need to squash these commits.

Thankyou so much!!

**Comment by ashrafhasson** [comment]
@hhff yeah no worries. I'm going to branch the computed property into its own as well and submit a PR for it, later on you can cherry-pick if you wish :)

**Comment by hhff** [comment]
@ashrafhasson YOU'RE THE MAN

**Comment by hhff** [comment]
@ashrafhasson if you rebase this against master & squash these commits down, your tests will pass.  Keen to merge this in!!!

**Pull request closed without merging**
