### PR TITLE
fixed wrong error message

### PR DESCRIPTION
**Pull request by cgwic**
about issue #25 
sorry not so familiar with github

### CODE REVIEW

**Comment by hhff** [comment]
Thankyou @cgwic !

@buschtoens explicitly moved `ember-cli-version-checker` to devDependencies.  What's the reason for moving it back?

https://github.com/hhff/ember-infinity/issues/16

**Comment by hhff** [comment]
@buschtoens - noticed `ember-cli-htmlbars` has it in dependencies:

https://github.com/ember-cli/ember-cli-htmlbars/blob/master/package.json

**Comment by cgwic** [comment]
@hhff i've got an error in [my project](https://github.com/cgwic/stream-fan), when trying to install last version of ember infinity or [my fork of it](https://github.com/cgwic/ember-infinity) and get rid of it simply adding  ```ember-cli-version-checker```.

Sorry, i may be wrong, but ```ember-cli-htmlbars``` installs ```ember-cli-version-checker``` in its own modules folder, so its still unreachable for ```ember-infinity```

**Comment by hhff** [comment]
Oh yeah got it, I was saying i guess the appropriate place for it is dependencies rather than devDependencies !

**Pull request merged**
