### PR TITLE
uses the override properties when loading more

### LINKED ISSUE #34: customizations not persisting
I'm trying this out in my app.
```
export default Ember.Route.extend(InfinityRoute, {
  model() {
    return this.infinityModel('user', { perPage: 10, startingPage: 1 });
  },

  perPageParam: 'pageSize'
});
```
The first request is
```
http://localhost/api/v1/users?page=1&pageSize=10
```
but the second request is
```
http://localhost/api/v1/users?page=2&per_page=10
```
The model hook is not getting called the second time if that helps.
```
ember-infinity@0.0.9
ember-cli@0.2.7
ember@1.12.1
ember-data@1.0.0-beta.18
jquery@2.1.4
```

### PR DESCRIPTION
**Pull request by kellyselden**
fixes #34

### CODE REVIEW

**Comment by hhff** [comment]
Thanks @kellyselden !!  Figured this was the problem.

Currently tests aren't passing on Travis because we're not Ember 2.0 compatible yet (and `ember-try` is attempting to test against it).  I won't have a chance to look into this until monday night coming.

**Comment by hhff** [comment]
@kellyselden if you rebase against master, tests will now be passing.  Keen to merge this!

**Comment by kellyselden** [comment]
Hopefully I can do this tonight

**Comment by kellyselden** [comment]
rebased

**Comment by hhff** [comment]
Da man

**Pull request merged**
