### PR TITLE
adds json response to README.md

### PR DESCRIPTION
**Pull request by mockra**
wasn't clear from the documentation that the server needed to include
the number of total pages in the response

https://github.com/hhff/ember-infinity/issues/12

I left the example data incomplete, since it would depend on each application.

Thanks!

### CODE REVIEW

**Comment by hhff** [comment]
Thanks @mockra I think this should probably go up under basic usage though - it's a pretty important piece of info!

**Comment by mockra** [comment]
I moved the added documentation up under Basic Usage with an h4 tag.

When this is ready to be merged, I'll go ahead and squash the commits.

**Comment by hhff** [comment]
:+1: get squashy with it!!!

**Comment by mockra** [comment]
squashed! thanks :sunglasses:

**Comment by hhff** [comment]
No thankyou!

**Pull request merged**
