### PR TITLE
verbose version of "Could not fetch Infinity Model"

### PR DESCRIPTION
**Pull request by etozzato**
Displays the error message related to the exception that triggers the “Ember Infinity: Could not fetch Infinity Model” error, making debugging a little easier.

### CODE REVIEW

**Comment by kellyselden** [comment]
:+1: Thank you!

**Comment by kellyselden** [comment]
Can you give us a sample of what the output would be now? Since it is untested (no unit tests), I'm a little hesitant to merge it.

**Comment by etozzato** [comment]
Sure, let me put my app back into the "failing mode" that led me to this PR :)

**Comment by davidgoli** [comment]
@hhff @kellyselden is there a good reason for us to catch and throw our own error here? Why not just let the original exception (eg. `AdapterError`) be the user exception?

**Comment by kellyselden** [comment]
Yeah I'm +1 for removing the catch. I don't know if it makes it easier to track who was responsible for sending the request or not. I think the stack trace can be just as useful.

**Comment by hhff** [comment]
I'm cool with loosing it also

**Comment by etozzato** [comment]
whether or not the catch goes away, I added a spec ;) :tada:

**Comment by philipp-spiess** [comment]
This will also swallow errors that can occur in production (ex. 500 errors). Remove the catching here completely as in #125

**Pull request closed without merging**
