### PR TITLE
Allow customization of pagination API

### PR DESCRIPTION
**Pull request by truenorth**
### Please merge #20 first

Currently this addon has the following request payload structure hardcoded

```js
{
  per_page: 10,
  page: 14
}
```
This PR allows customization of these two parameters, so that you could work with an API that expects to recieve something like
```js
{
  per: 10,
  p: 14
}
```

### CODE REVIEW

**Comment by hhff** [comment]
This is awesome @truenorth !  Thankyou.  Can you update the README with this?  Under "Advanced Usage" for infinityModel makes most sense I think :+1: 

Might be worth allowing the developer to customize where ember infinity looks for the total_pages in the server response too - but I'm happy to merge this regardless.

**Comment by truenorth** [comment]
Sure I'll add more complete customization, test coverage and documentation. Sent from Yahoo Mail for iPhoneAt May 19, 2015, 01:57:40, Hugh Francis wrote:This is awesome @truenorth !  Thankyou.  Can you update the README with this?  Under "Advanced Usage" for infinityModel makes most sense I think  

Might be worth allowing the developer to customize where ember infinity looks for the total_pages in the server response too - but I'm happy to merge this regardless.

**Comment by hhff** [comment]
Thankyou mike - this will be awesome!

**Comment by truenorth** [comment]
@hhff this should be ready to go now

**Comment by hhff** [comment]
LGTM :+1: Please rebase

**Comment by truenorth** [comment]
@hhff Squashed. Please make sure to merge #20 first and then this PR will just be one commit

**Pull request merged**
