### PR TITLE
Fix deprecation warning about didInsertElement modification

### PR DESCRIPTION
**Pull request by JoepHeijnen**
This should fix the following deprecation warning for <= Ember 2.3.0.

>DEPRECATION: A property of <PROJECT@view:-outlet::ember1154> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]

### CODE REVIEW

**Comment by snewcomer** [comment]
@JoepHeijnen Nice!  Do you have a link to the dep warning if there was one?  Also, curious, what version of Ember are you running?

**Comment by JoepHeijnen** [comment]
@snewcomer [Link](https://emberjs.com/deprecations/v1.x/#toc_modifying-a-property-within-code-didinsertelement-code). At the moment I am running on Ember 2.3.2.

**Comment by snewcomer** [comment]
@JoepHeijnen cool thanks for the link.  The polyfill - do you have master or 0.2.8 installed?  Can you try adding this and see if it solves the problem you were seeing instead? 

```
var app = new EmberApp(defaults, {
  // Add options here
  babel: {
    includePolyfill: true
  }
});
```

**Comment by snewcomer** [comment]
@JoepHeijnen sry that was some bad advice on my part.  Shouldn't require the use of the babel polyfill.  I took what you suggested and put it in a util file [here](https://github.com/hhff/ember-infinity/pull/215/commits/eb1f54ea70179aaa2574f7d994970ad944c0113b).  Can you let me know what you think of this?

**Comment by JoepHeijnen** [comment]
@snewcomer Looks good to me. Much cleaner than my implementation ;)

**Comment by snewcomer** [comment]
@JoepHeijnen could you pop off that last commit?  Also, I think there is something else going on here.  Yeah calling `didInsertElement` and setting a property will call a re-render.  Let me dig into this.  Going to be making some bigger changes soon, so I'll ping ya!

**Pull request closed without merging**
